#: kivy 1.9.0

<FlowchartExampleWidget>
	drag_grid: drag_grid
	size:root.size
	FloatLayout:
		size:root.size
		BoxLayout:
			orientation: 'horizontal'
			size: root.size
			BoxLayout:
				orientation: 'vertical'
				size_hint: 0.2, 1
				id: box_layout
				FloatLayout:
					BoxLayout:
					GridLayout:
						id: grid_layout
						rows: int(self.height / 20)
					FloatLayout:
						id: float_layout
			DragGrid:
				size_hint: 0.8, 1
				size: 8
				id: drag_grid